# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MongoBinaryDirectory: /usr/bin/mongo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Directory
      run: echo $MongoBinaryDirectory
    - name: action-mongo-tools
      uses: boly38/action-mongo-tools@v1.0.1
    - name: Check Mongo Install Directory
      run: locate -b '\mongo'
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
